vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /uploads/images/eleves
    #        upload_destination: '%kernel.project_dir%/public/uploads/images/eleves'
    mappings:
        eleve_images:
            uri_prefix:         '%app.path.eleve_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.eleve_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true